# Generated by Django 4.2.3 on 2023-07-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBooking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('b_property_name', models.CharField(max_length=100)),
                ('b_purchaser_name', models.CharField(max_length=100)),
                ('b_place', models.CharField(max_length=100)),
                ('b_amount', models.CharField(max_length=100)),
                ('b_date', models.CharField(max_length=100)),
                ('b_status', models.IntegerField(default=0)),
                ('b_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_mobile', models.CharField(max_length=100)),
                ('ad_email', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
                ('ad_role', models.CharField(default='', max_length=100)),
                ('ad_status', models.IntegerField(default=0)),
                ('ad_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminSeller',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('s_name', models.CharField(max_length=100)),
                ('s_mobile', models.CharField(max_length=100)),
                ('s_email', models.CharField(max_length=100)),
                ('s_password', models.CharField(default='', max_length=100)),
                ('s_role', models.CharField(default='', max_length=100)),
                ('s_address', models.CharField(default='', max_length=200)),
                ('s_status', models.IntegerField(default=0)),
                ('s_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bk_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bk_user_name', models.CharField(max_length=100)),
                ('bk_user_email', models.CharField(max_length=100)),
                ('bk_user_phone', models.CharField(default='', max_length=100)),
                ('bk_seller_name', models.CharField(max_length=100)),
                ('bk_seller_email', models.CharField(max_length=100)),
                ('bk_user_address', models.CharField(default='', max_length=100)),
                ('bk_property_id', models.CharField(max_length=100)),
                ('bk_amount', models.CharField(max_length=100)),
                ('bk_status', models.CharField(default=0, max_length=100)),
                ('bk_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ca_name', models.CharField(max_length=100)),
                ('ca_status', models.IntegerField(default=0)),
                ('ca_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pr_image', models.ImageField(default='', upload_to='app/static/media/property/')),
                ('pr_name', models.CharField(default='', max_length=100)),
                ('pr_seller_name', models.CharField(max_length=100)),
                ('pr_category', models.CharField(default='', max_length=100)),
                ('pr_property_type', models.CharField(max_length=100)),
                ('pr_place', models.CharField(max_length=100)),
                ('pr_fee', models.CharField(default='', max_length=100)),
                ('pr_desc', models.CharField(default='', max_length=500)),
                ('pr_date', models.CharField(max_length=100)),
                ('pr_mobile_no', models.CharField(max_length=100)),
                ('pr_status', models.IntegerField(default=0)),
                ('pr_sold', models.CharField(default='NO', max_length=100)),
                ('pr_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('us_name', models.CharField(default='', max_length=100)),
                ('us_email', models.CharField(max_length=100)),
                ('us_mobile', models.CharField(default='', max_length=100)),
                ('us_password', models.CharField(max_length=100)),
                ('us_status', models.IntegerField(default=0)),
                ('us_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
