# Generated by Django 4.2.4 on 2023-08-25 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bk_created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
