# Generated by Django 4.0 on 2024-12-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_bk_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pd_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pd_image', models.ImageField(default='', upload_to='app/static/media/property/')),
                ('pd_name', models.CharField(default='', max_length=100)),
                ('pd_category', models.CharField(default='', max_length=100)),
                ('pd_fee', models.CharField(default='', max_length=100)),
                ('pd_desc', models.CharField(default='', max_length=500)),
                ('pd_date', models.CharField(max_length=100)),
                ('pd_status', models.IntegerField(default=0)),
                ('pd_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
