# Generated by Django 4.0 on 2024-12-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pd_fee',
            new_name='pd_price',
        ),
    ]
