# Generated by Django 4.0 on 2024-12-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_pd_fee_products_pd_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_image', models.CharField(default='', max_length=200)),
                ('ct_name', models.CharField(default='', max_length=100)),
                ('ct_category', models.CharField(default='', max_length=100)),
                ('ct_price', models.CharField(default='', max_length=100)),
                ('ct_desc', models.CharField(default='', max_length=500)),
                ('ct_user_email', models.CharField(default='', max_length=100)),
                ('ct_status', models.IntegerField(default=0)),
                ('ct_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
