# Generated by Django 4.0 on 2024-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ct_qty',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='ct_total_amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
