# Generated by Django 4.0 on 2024-12-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_ct_qty_cart_ct_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('or_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('or_name', models.CharField(default='', max_length=100)),
                ('or_date', models.CharField(default='', max_length=100)),
                ('or_transaction_id', models.CharField(default='', max_length=100)),
                ('or_mobile', models.CharField(default='', max_length=100)),
                ('or_email', models.CharField(default='', max_length=100)),
                ('or_address', models.CharField(default='', max_length=500)),
                ('or_total_amount', models.CharField(default='', max_length=100)),
                ('or_user_email', models.CharField(default='', max_length=100)),
                ('or_status', models.IntegerField(default=0)),
                ('or_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('pp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pp_or_id', models.CharField(default='', max_length=200)),
                ('pp_image', models.CharField(default='', max_length=200)),
                ('pp_name', models.CharField(default='', max_length=100)),
                ('pp_category', models.CharField(default='', max_length=100)),
                ('pp_price', models.CharField(default='', max_length=100)),
                ('pp_desc', models.CharField(default='', max_length=500)),
                ('pp_qty', models.CharField(default='', max_length=100)),
                ('pp_total_amount', models.CharField(default='', max_length=100)),
                ('pp_user_email', models.CharField(default='', max_length=100)),
                ('pp_status', models.IntegerField(default=0)),
                ('pp_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
