# Generated by Django 4.0 on 2024-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_purchasedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='or_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
