# Generated by Django 4.0 on 2024-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_or_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='pr_image1',
            field=models.ImageField(default='', upload_to='app/static/media/property/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='pr_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='pd_desc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
