# Generated by Django 6.0.2 on 2026-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_properties_pr_image1_properties_pr_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='products',
            name='pd_image',
            field=models.ImageField(default='', upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pr_image',
            field=models.ImageField(default='', upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pr_image1',
            field=models.ImageField(default='', upload_to='property/'),
        ),
    ]
