"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY: SECRET KEY
# =============================================================================
# Read from environment variable in production.
# Fallback is ONLY for local development — NEVER use the fallback in production.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "xc@j_in54!hrh(o3lchh$s1jmyado3pk31c3kbodtdcz0@aa4r"  # Dev fallback only
)

# =============================================================================
# SECURITY: DEBUG MODE
# =============================================================================
# DEBUG=False by default (production-safe).
# Set DJANGO_DEBUG=True in your local environment for development.
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes")

# =============================================================================
# ALLOWED HOSTS
# =============================================================================
ALLOWED_HOSTS = [
    "estatehub.pythonanywhere.com",  # Production
    ".pythonanywhere.com",            # Any PA subdomain (future-proof)
    "localhost",                      # Local development
    "127.0.0.1",                      # Local development
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "project",
#         "USER": "root",
#         "PASSWORD": "",
#         "HOST": "localhost",  # Or an IP Address that your DB is hosted on
#         "PORT": "3306",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "app/static"),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = ""  # your email id
EMAIL_HOST_PASSWORD = ""  # password


# =============================================================================
# DEFAULT AUTO FIELD (suppresses Django 3.2+ warnings)
# =============================================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# SECURITY HEADERS — Production hardening
# =============================================================================
# Prevent the browser from MIME-sniffing a response away from the declared type
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enable the browser's XSS filter (legacy but still useful)
SECURE_BROWSER_XSS_FILTER = True

# Prevent this site from being embedded in iframes (clickjacking protection)
X_FRAME_OPTIONS = "DENY"

# Session security
SESSION_COOKIE_HTTPONLY = True     # JS cannot access session cookie
SESSION_COOKIE_AGE = 3600         # Session expires after 1 hour (seconds)
SESSION_SAVE_EVERY_REQUEST = True  # Reset expiry timer on each request

# =============================================================================
# PRODUCTION-ONLY SECURITY (only active when DEBUG=False)
# =============================================================================
if not DEBUG:
    # Only send cookies over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Redirect HTTP to HTTPS (PythonAnywhere handles this, but belt-and-suspenders)
    SECURE_SSL_REDIRECT = False  # PA handles SSL termination; set True if you want Django to enforce

    # HSTS: tell browsers to always use HTTPS for this site
    SECURE_HSTS_SECONDS = 31536000        # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# =============================================================================
# LOGIN RATE LIMITING CONFIGURATION
# =============================================================================
# Session-based brute-force protection (no extra dependencies needed)
LOGIN_MAX_ATTEMPTS = 5          # Max failed login attempts before lockout
LOGIN_LOCKOUT_DURATION = 1800   # Lockout duration in seconds (30 minutes)
